#!/usr/bin/env node
// Generate a Mermaid C4 module dependency map for the Rust mmdflux crate.

import { parseArgs } from 'node:util';
import { existsSync } from 'node:fs';
import { dirname, basename, resolve } from 'node:path';
import {
  discoverModules, collectDependencies, collapseLabel, writeOutput,
} from './core.mjs';

const { values } = parseArgs({
  options: {
    'crate-root': { type: 'string', default: 'src/lib.rs' },
    'max-depth': { type: 'string', default: '1' },
    'shapes-per-row': { type: 'string', default: '4' },
    output: { type: 'string' },
    help: { type: 'boolean', short: 'h' },
  },
  strict: true,
});

if (values.help) {
  console.log(`Usage: c4.mjs [options]

Options:
  --crate-root <path>      Crate root file (default: src/lib.rs)
  --max-depth <n>          Collapse depth (default: 1)
  --shapes-per-row <n>     C4 layout shapes per row (default: 4)
  --output <path>          Write to file instead of stdout
  -h, --help               Show this help`);
  process.exit(0);
}

const crateRoot = values['crate-root'];
const maxDepth = Number(values['max-depth']);
const shapesPerRow = Number(values['shapes-per-row']);

if (maxDepth < 1) { console.error('--max-depth must be >= 1'); process.exit(2); }
if (shapesPerRow < 1) { console.error('--shapes-per-row must be >= 1'); process.exit(2); }
if (!existsSync(crateRoot)) {
  console.error(`crate root does not exist: ${crateRoot}`); process.exit(2);
}

function componentId(label) { return 'mod_' + label.replace(/::/g, '_'); }

const resolvedRoot = resolve(crateRoot);
const crateName = basename(dirname(dirname(resolvedRoot))) || 'crate';

const modules = discoverModules(crateRoot);
const dependencies = collectDependencies(modules);

// Collapse nodes and track member counts
const groupedNodes = new Set();
const groupedMembers = new Map();
for (const label of modules.keys()) {
  if (label === '') continue;
  const collapsed = collapseLabel(label, maxDepth);
  groupedNodes.add(collapsed);
  if (!groupedMembers.has(collapsed)) groupedMembers.set(collapsed, new Set());
  groupedMembers.get(collapsed).add(label);
}

// Collapse edges
const edgeSeen = new Set();
const edgePairs = [];
for (const [source, targets] of dependencies) {
  const cs = collapseLabel(source, maxDepth);
  for (const target of targets) {
    const ct = collapseLabel(target, maxDepth);
    if (cs === ct) continue;
    const key = `${cs}\0${ct}`;
    if (!edgeSeen.has(key)) { edgeSeen.add(key); edgePairs.push([cs, ct]); }
  }
}
edgePairs.sort((a, b) =>
  a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : (a[1] < b[1] ? -1 : a[1] > b[1] ? 1 : 0));

function componentKind(label) {
  return groupedMembers.get(label).size > 1 ? 'Rust module group' : 'Rust module';
}

const lines = [
  '%% Generated by scripts/module-deps/c4.mjs',
  `%% crate-root: ${crateRoot}`,
  `%% max-depth: ${maxDepth}`,
  'C4Component',
  `UpdateLayoutConfig($c4ShapeInRow="${shapesPerRow}", $c4BoundaryInRow="1")`,
  `Boundary(main_crate, "${crateName} crate", "Rust crate") {`,
];

for (const node of [...groupedNodes].sort()) {
  lines.push(`    Component(${componentId(node)}, "${node}", "${componentKind(node)}")`);
}
lines.push('}');

for (const [source, target] of edgePairs) {
  lines.push(`    Rel(${componentId(source)}, ${componentId(target)}, "uses")`);
}

const diagram = lines.join('\n') + '\n';
writeOutput(diagram, values.output || null);
