#!/usr/bin/env node
// Generate a Mermaid module dependency map for the Rust mmdflux crate.

import { parseArgs } from 'node:util';
import { existsSync } from 'node:fs';
import {
  discoverModules, collectDependencies, collapseLabel, writeOutput,
} from './core.mjs';

const { values } = parseArgs({
  options: {
    'crate-root': { type: 'string', default: 'src/lib.rs' },
    'max-depth': { type: 'string', default: '1' },
    direction: { type: 'string', default: 'LR' },
    output: { type: 'string' },
    help: { type: 'boolean', short: 'h' },
  },
  strict: true,
});

if (values.help) {
  console.log(`Usage: flowchart.mjs [options]

Options:
  --crate-root <path>   Crate root file (default: src/lib.rs)
  --max-depth <n>       Collapse depth (default: 1)
  --direction <dir>     LR, RL, TB, or BT (default: LR)
  --output <path>       Write to file instead of stdout
  -h, --help            Show this help`);
  process.exit(0);
}

const crateRoot = values['crate-root'];
const maxDepth = Number(values['max-depth']);
const direction = values.direction;

if (maxDepth < 1) { console.error('--max-depth must be at least 1'); process.exit(2); }
if (!['LR', 'RL', 'TB', 'BT'].includes(direction)) {
  console.error('--direction must be LR, RL, TB, or BT'); process.exit(2);
}
if (!existsSync(crateRoot)) {
  console.error(`crate root does not exist: ${crateRoot}`); process.exit(2);
}

function nodeId(label) { return 'mod_' + label.replace(/::/g, '_'); }

const modules = discoverModules(crateRoot);
const dependencies = collectDependencies(modules);

// Collapse nodes and edges
const groupedNodes = new Set();
for (const label of modules.keys()) {
  if (label !== '') groupedNodes.add(collapseLabel(label, maxDepth));
}

const edgeSeen = new Set();
const edgePairs = [];
for (const [source, targets] of dependencies) {
  const cs = collapseLabel(source, maxDepth);
  for (const target of targets) {
    const ct = collapseLabel(target, maxDepth);
    if (cs && ct && cs !== ct) {
      const key = `${cs}\0${ct}`;
      if (!edgeSeen.has(key)) { edgeSeen.add(key); edgePairs.push([cs, ct]); }
    }
  }
}
edgePairs.sort((a, b) =>
  a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : (a[1] < b[1] ? -1 : a[1] > b[1] ? 1 : 0));

// Group nodes by top-level module
const byTopLevel = new Map();
for (const label of [...groupedNodes].sort()) {
  const top = label.split('::')[0];
  if (!byTopLevel.has(top)) byTopLevel.set(top, []);
  byTopLevel.get(top).push(label);
}

const lines = [
  '%% Generated by scripts/module-deps/flowchart.mjs',
  `%% crate-root: ${crateRoot}`,
  `%% max-depth: ${maxDepth}`,
  `flowchart ${direction}`,
];

for (const top of [...byTopLevel.keys()].sort()) {
  const nodes = byTopLevel.get(top);
  if (nodes.length === 1 && !nodes[0].includes('::')) {
    lines.push(`    ${nodeId(nodes[0])}["${nodes[0]}"]`);
    continue;
  }
  lines.push(`    subgraph group_${top}["${top}"]`);
  for (const node of nodes) lines.push(`        ${nodeId(node)}["${node}"]`);
  lines.push('    end');
}

for (const [source, target] of edgePairs) {
  lines.push(`    ${nodeId(source)} --> ${nodeId(target)}`);
}

const diagram = lines.join('\n') + '\n';

if (values.output) {
  writeOutput(diagram, values.output);
  console.error(
    `wrote Mermaid dependency map to ${values.output} (${modules.size - 1} modules discovered)`,
  );
} else {
  writeOutput(diagram, null);
}
