#!/usr/bin/env node
// Generate a Mermaid SCC-condensed dependency DAG for Rust modules.

import { parseArgs } from 'node:util';
import { existsSync } from 'node:fs';
import {
  discoverModules, collectDependencies, collapseGraph,
  tarjanScc, buildCondensationGraph, topologicalOrder, writeOutput,
} from './core.mjs';

const { values } = parseArgs({
  options: {
    'crate-root': { type: 'string', default: 'src/lib.rs' },
    'max-depth': { type: 'string', default: '1' },
    direction: { type: 'string', default: 'LR' },
    'members-per-line': { type: 'string', default: '3' },
    output: { type: 'string' },
    help: { type: 'boolean', short: 'h' },
  },
  strict: true,
});

if (values.help) {
  console.log(`Usage: scc.mjs [options]

Options:
  --crate-root <path>        Crate root file (default: src/lib.rs)
  --max-depth <n>            Collapse depth (default: 1)
  --direction <dir>          LR, RL, TB, or BT (default: LR)
  --members-per-line <n>     SCC label line width (default: 3)
  --output <path>            Write to file instead of stdout
  -h, --help                 Show this help`);
  process.exit(0);
}

const crateRoot = values['crate-root'];
const maxDepth = Number(values['max-depth']);
const direction = values.direction;
const membersPerLine = Number(values['members-per-line']);

if (maxDepth < 1) { console.error('--max-depth must be >= 1'); process.exit(2); }
if (membersPerLine < 1) { console.error('--members-per-line must be >= 1'); process.exit(2); }
if (!['LR', 'RL', 'TB', 'BT'].includes(direction)) {
  console.error('--direction must be LR, RL, TB, or BT'); process.exit(2);
}
if (!existsSync(crateRoot)) {
  console.error(`crate root does not exist: ${crateRoot}`); process.exit(2);
}

function sccId(index) { return `scc_${index}`; }

function sccLabel(component) {
  if (component.length === 1) return component[0];
  const lines = [`cycle (${component.length} modules)`];
  for (let i = 0; i < component.length; i += membersPerLine) {
    lines.push(component.slice(i, i + membersPerLine).join(', '));
  }
  return lines.join('<br/>');
}

const modules = discoverModules(crateRoot);
const dependencies = collectDependencies(modules);
const { edges: groupedEdges } = collapseGraph(modules, dependencies, maxDepth);
const components = tarjanScc(new Set(groupedEdges.keys()), groupedEdges);
const { componentNodes, condensationEdges } = buildCondensationGraph(components, groupedEdges);
const ordered = topologicalOrder(componentNodes, condensationEdges);

const multi = [...componentNodes].filter(([, m]) => m.length > 1).map(([id]) => id);
const single = [...componentNodes].filter(([, m]) => m.length === 1).map(([id]) => id);

const lines = [
  '%% Generated by scripts/module-deps/scc.mjs',
  `%% crate-root: ${crateRoot}`,
  `%% max-depth: ${maxDepth}`,
  `%% component-count: ${componentNodes.size}`,
  `%% largest-scc-size: ${Math.max(...[...componentNodes.values()].map(c => c.length))}`,
  `flowchart ${direction}`,
];

for (const cid of ordered) {
  lines.push(`    ${sccId(cid)}["${sccLabel(componentNodes.get(cid))}"]`);
}

for (const source of ordered) {
  for (const target of [...(condensationEdges.get(source) || [])].sort((a, b) => a - b)) {
    lines.push(`    ${sccId(source)} --> ${sccId(target)}`);
  }
}

lines.push(
  '    classDef cycle fill:#fbe4e6,stroke:#b42318,stroke-width:2px,color:#1f2937;',
  '    classDef singleton fill:#e8f0ff,stroke:#4f46e5,stroke-width:1.5px,color:#1f2937;',
);

if (multi.length) {
  lines.push('    class ' + multi.sort((a, b) => a - b).map(sccId).join(',') + ' cycle;');
}
if (single.length) {
  lines.push('    class ' + single.sort((a, b) => a - b).map(sccId).join(',') + ' singleton;');
}

const diagram = lines.join('\n') + '\n';
writeOutput(diagram, values.output || null);
