[env]
_.path = [
  "{{config_root}}/target/release",
  "{{config_root}}/target/debug",
  "{{config_root}}/packages/node_modules/.bin",
]

[tools]
github-cli = "latest"
jq = "latest"
just = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:wasm-pack" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"


[tools.node]
version = "lts"
corepack = true

[tools."cargo:cocogitto"]
version = "6.5"
postinstall = "cog install-hook --all --overwrite"

[settings]
experimental = true
